server {
  listen 80; # port my server listens on

  location /health {
    handler HealthHandler; # returns 200 OK with "OK" body
  }

  location /echo {
    handler EchoHandler; # no arguments
  }

  location /static {
    handler StaticHandler;
    root /assets; # supports relative paths
  }

  location /bathroom-map {
    handler StaticHandler;
    root /assets/bathroom-map;
  }

  location /api {
    handler ApiHandler;
    data_path /mnt/crud;
  }
}
