#include "gtest/gtest.h"
#include "response_builder.h"

class ResponseBuilderTest : public ::testing::Test {
protected:
// function is generated by ai
  std::string SerializeResponse(const std::unique_ptr<response>& response_obj) {
    if (!response_obj) {
        return "";
    }
    std::string response_str;
    response_str.append("HTTP/1.1 " + response_obj->status_code + "\r\n");
    for(const auto& header : response_obj->headers) {
        response_str.append(header + "\r\n");
    }
    response_str.append("\r\n" + response_obj->body);
    return response_str;
  }

  void ValidateResponseFormat(const std::string& response,
                              const std::string& expected_status,
                              const std::string& expected_content_type,
                              const std::string& expected_body) {
    // Check status line
    EXPECT_TRUE(response.find("HTTP/1.1 " + expected_status) != std::string::npos);
    
    // Check content type header
    EXPECT_TRUE(response.find("Content-Type: " + expected_content_type) != std::string::npos);
    
    // Check content length header
    std::string content_length = "Content-Length: " + std::to_string(expected_body.size());
    EXPECT_TRUE(response.find(content_length) != std::string::npos);
    
    // Check connection header
    EXPECT_TRUE(response.find("Connection: close") != std::string::npos);
    
    // Check body is at the end
    EXPECT_TRUE(response.find("\r\n\r\n" + expected_body) != std::string::npos);
  }
};

// Test Ok response with default content type
TEST_F(ResponseBuilderTest, OkResponseDefault) {
  std::string body = "Success!";
  auto response_obj = ResponseBuilder::Ok(body);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "200 OK", "text/plain", body);
}

// Test Ok response with custom content type
TEST_F(ResponseBuilderTest, OkResponseCustomContentType) {
  std::string body = "<html><body>Hello</body></html>";
  auto response_obj = ResponseBuilder::Ok(body, "text/html");
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "200 OK", "text/html", body);
}

// Test Ok response with JSON content type
TEST_F(ResponseBuilderTest, OkResponseJSON) {
  std::string body = "{\"status\":\"ok\"}";
  auto response_obj = ResponseBuilder::Ok(body, "application/json");
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "200 OK", "application/json", body);
}

// Test Ok response with empty body
TEST_F(ResponseBuilderTest, OkResponseEmptyBody) {
  std::string body = "";
  auto response_obj = ResponseBuilder::Ok(body);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "200 OK", "text/plain", body);
  EXPECT_TRUE(response.find("Content-Length: 0") != std::string::npos);
}

// Test NotFound response with default message
TEST_F(ResponseBuilderTest, NotFoundDefault) {
  auto response_obj = ResponseBuilder::NotFound();
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "404 Not Found", "text/plain", "404 Not Found");
}

// Test NotFound response with custom message
TEST_F(ResponseBuilderTest, NotFoundCustomMessage) {
  std::string message = "Page not found";
  auto response_obj = ResponseBuilder::NotFound(message);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "404 Not Found", "text/plain", message);
}

// Test Forbidden response with default message
TEST_F(ResponseBuilderTest, ForbiddenDefault) {
  auto response_obj = ResponseBuilder::Forbidden();
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "403 Forbidden", "text/plain", "403 Forbidden");
}

// Test Forbidden response with custom message
TEST_F(ResponseBuilderTest, ForbiddenCustomMessage) {
  std::string message = "Access denied";
  auto response_obj = ResponseBuilder::Forbidden(message);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "403 Forbidden", "text/plain", message);
}

// Test BadRequest response with default message
TEST_F(ResponseBuilderTest, BadRequestDefault) {
  auto response_obj = ResponseBuilder::BadRequest();
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "400 Bad Request", "text/plain", "400 Bad Request");
}

// Test BadRequest response with custom message
TEST_F(ResponseBuilderTest, BadRequestCustomMessage) {
  std::string message = "Invalid request format";
  auto response_obj = ResponseBuilder::BadRequest(message);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "400 Bad Request", "text/plain", message);
}

// Test InternalServerError response with default message
TEST_F(ResponseBuilderTest, InternalServerErrorDefault) {
  auto response_obj = ResponseBuilder::InternalServerError();
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "500 Internal Server Error", "text/plain", 
                        "500 Internal Server Error");
}

// Test InternalServerError response with custom message
TEST_F(ResponseBuilderTest, InternalServerErrorCustomMessage) {
  std::string message = "Database connection failed";
  auto response_obj = ResponseBuilder::InternalServerError(message);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "500 Internal Server Error", "text/plain", message);
}

// Test MethodNotAllowed response with default message
TEST_F(ResponseBuilderTest, MethodNotAllowedDefault) {
  auto response_obj = ResponseBuilder::MethodNotAllowed();
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "405 Method Not Allowed", "text/plain", 
                        "405 Method Not Allowed");
}

// Test MethodNotAllowed response with custom message
TEST_F(ResponseBuilderTest, MethodNotAllowedCustomMessage) {
  std::string message = "POST method not supported";
  auto response_obj = ResponseBuilder::MethodNotAllowed(message);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "405 Method Not Allowed", "text/plain", message);
}

// Test BuildResponse with custom status code
TEST_F(ResponseBuilderTest, BuildResponseCustomStatus) {
  std::string body = "Created successfully";
  auto response_obj = ResponseBuilder::BuildResponse("201 Created", "text/plain", body);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "201 Created", "text/plain", body);
}

// Test response with large body
TEST_F(ResponseBuilderTest, LargeBody) {
  std::string body(10000, 'A');  // 10,000 'A' characters
  auto response_obj = ResponseBuilder::Ok(body);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "200 OK", "text/plain", body);
  EXPECT_TRUE(response.find("Content-Length: 10000") != std::string::npos);
}

// Test response with special characters in body
TEST_F(ResponseBuilderTest, SpecialCharactersInBody) {
  std::string body = "Special chars: \r\n\t!@#$%^&*()";
  auto response_obj = ResponseBuilder::Ok(body);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "200 OK", "text/plain", body);
}

// Test response with multiline body
TEST_F(ResponseBuilderTest, MultilineBody) {
  std::string body = "Line 1\r\nLine 2\r\nLine 3";
  auto response_obj = ResponseBuilder::Ok(body);
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "200 OK", "text/plain", body);
}

// Test response header order
TEST_F(ResponseBuilderTest, HeaderOrder) {
  auto response_obj = ResponseBuilder::Ok("test");
  std::string response = SerializeResponse(response_obj);
  
  size_t status_pos = response.find("HTTP/1.1");
  size_t content_type_pos = response.find("Content-Type:");
  size_t content_length_pos = response.find("Content-Length:");
  size_t connection_pos = response.find("Connection:");
  size_t body_pos = response.find("\r\n\r\n");
  
  // Verify header order
  EXPECT_LT(status_pos, content_type_pos);
  EXPECT_LT(content_type_pos, content_length_pos);
  EXPECT_LT(content_length_pos, connection_pos);
  EXPECT_LT(connection_pos, body_pos);
}

// Test CSS content type
TEST_F(ResponseBuilderTest, CSSContentType) {
  std::string body = "body { color: red; }";
  auto response_obj = ResponseBuilder::Ok(body, "text/css");
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "200 OK", "text/css", body);
}

// Test JavaScript content type
TEST_F(ResponseBuilderTest, JavaScriptContentType) {
  std::string body = "console.log('hello');";
  auto response_obj = ResponseBuilder::Ok(body, "application/javascript");
  std::string response = SerializeResponse(response_obj);
  
  ValidateResponseFormat(response, "200 OK", "application/javascript", body);
}
