steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/insert-cheesy-bread:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'insert-cheesy-bread:base',
    '-t', 'gcr.io/$PROJECT_ID/insert-cheesy-bread:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/insert-cheesy-bread:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/insert-cheesy-bread:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/insert-cheesy-bread:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/insert-cheesy-bread:coverage',
    '.'
  ]
images: ['gcr.io/$PROJECT_ID/insert-cheesy-bread:base', 'gcr.io/$PROJECT_ID/insert-cheesy-bread:latest']
