#include <cstdlib>
#include <iostream>
#include <boost/bind.hpp>
#include <boost/asio.hpp>
#include <boost/log/trivial.hpp>

#include "session.h"
#include "request_parser.h"
#include "request_handler.h"
#include "request_handler_echo.h"
#include "request_handler_file.h"
#include "response_builder.h"

using boost::asio::ip::tcp;

session::session(boost::asio::io_service& io_service, std::shared_ptr<RequestDispatcher> dispatcher) 
    : socket_(io_service), dispatcher_(dispatcher)
{
}

tcp::socket& session::socket()
{
    return socket_;
}

// Helper: Start async read operation (reduces duplication)
void session::StartAsyncRead() {
    if (socket_.is_open()) {
        BOOST_LOG_TRIVIAL(debug) << "Starting async read";
    } else {
        BOOST_LOG_TRIVIAL(debug) << "Starting async read on unopened socket";
    }
    socket_.async_read_some(boost::asio::buffer(data_, max_length),
        boost::bind(&session::handle_read, this,
            boost::asio::placeholders::error,
            boost::asio::placeholders::bytes_transferred));
}

// Helper: Handle error case (reduces duplication)
void session::HandleError() {
    BOOST_LOG_TRIVIAL(error) << "Handling error for session from " << ip << ":" << port;
    delete this;
}

// Helper: Log structured response metrics
void session::LogResponseMetrics(const std::unique_ptr<response>& resp_obj, 
                                  const std::string& request_path,
                                  const std::string& handler_name) {
    if (!resp_obj) {
        return;
    }
    
    // Extract response code (e.g., "200 OK" -> "200")
    std::string response_code = resp_obj->status_code;
    size_t space_pos = response_code.find(' ');
    if (space_pos != std::string::npos) {
        response_code = response_code.substr(0, space_pos);
    }
    
    // Log structured metrics with [ResponseMetrics] tag for easy searching
    BOOST_LOG_TRIVIAL(info) << "[ResponseMetrics] response_code=\"" << response_code 
                            << "\" request_path=\"" << request_path
                            << "\" request_ip=\"" << ip
                            << "\" handler_name=\"" << handler_name << "\"";
}

// Helper: Send response to client
void session::SendResponse() {
    BOOST_LOG_TRIVIAL(debug) << "Sending response to client " << ip << ":" << port;
    boost::asio::async_write(socket_,
        boost::asio::buffer(response_),
        boost::bind(&session::handle_write, this,
            boost::asio::placeholders::error));
}
// function is generated by ai
std::string session::SerializeResponse(const std::unique_ptr<response>& response_obj) {
    if (!response_obj) {
        auto err_resp = ResponseBuilder::InternalServerError();
        return SerializeResponse(err_resp);
    }

    std::string response_str;
    response_str.append("HTTP/1.1 " + response_obj->status_code + "\r\n");
    for(const auto& header : response_obj->headers) {
        response_str.append(header + "\r\n");
    }
    response_str.append("\r\n" + response_obj->body);
    return response_str;
}

void session::start()
{
    auto endpoint = socket_.remote_endpoint();
    BOOST_LOG_TRIVIAL(info) << "New session started from " << endpoint.address().to_string() << ":" << endpoint.port();
    ip = endpoint.address().to_string();
    port = endpoint.port();
    BOOST_LOG_TRIVIAL(info) << "Starting session from " << ip << ":" << port;
    StartAsyncRead();
}

void session::handle_read(const boost::system::error_code& error, size_t bytes_transferred)
{
    if (!error)
    {
        request_buffer_.append(data_, bytes_transferred);
        BOOST_LOG_TRIVIAL(info) << "Request from " << ip << ":" << port << " is " << request_buffer_; 
        BOOST_LOG_TRIVIAL(info) << "Request contains " << request_buffer_.size() << " bytes";
        
        // Validate and parse HTTP request
        RequestParser parser;
        request request;
        bool isComplete = parser.Parse(request_buffer_, request);
        if (isComplete) {
            if (!request.is_valid) {
                auto resp_obj = ResponseBuilder::BadRequest();
                std::string request_path = request.url.empty() ? "<unknown>" : request.url;
                LogResponseMetrics(resp_obj, request_path, "BadRequest");
                response_ = SerializeResponse(resp_obj);
                SendResponse();
            }
            else {
                auto handler = dispatcher_->CreateHandler(request.url);
                
                // Dispatcher always returns a handler (matched handler or NotFoundHandler)
                auto resp_obj = handler->handle_request(request);
                std::string handler_name = handler->GetHandlerName();
                LogResponseMetrics(resp_obj, request.url, handler_name);
                response_ = SerializeResponse(resp_obj);
                SendResponse();
            }
        } else {
            // Continue reading more data
            StartAsyncRead();
        }
    }
    else
    {
        if (error == boost::asio::error::eof || error == boost::asio::error::connection_reset) {
            BOOST_LOG_TRIVIAL(info) << "Client " << ip << ":" << port << " disconnected";
        } else {
            BOOST_LOG_TRIVIAL(warning) << "Read error from " << ip << ":" << port << " — " << error.message();
        }
        HandleError();  
    }
}

void session::handle_write(const boost::system::error_code& error)
{
    BOOST_LOG_TRIVIAL(debug) << "Handling write operation for client " << ip << ":" << port;
    if (!error)
    {
        StartAsyncRead();
    }
    else
    {
        HandleError();
    }
}
